#!/usr/bin/env python3
"""Build deterministic CHF git-history fixtures from scenario files."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCENARIOS_DIR = ROOT / "scenarios"
FIXTURE_TIMESTAMP = "2026-06-01T00:00:00+05:30"

AUTHORS = {
    "platform": ("Kavya Menon", "kavya.menon@example.com"),
    "release": ("Dev Malhotra", "dev.malhotra@example.com"),
    "airtel": ("Neha Rao", "neha.rao@example.com"),
    "reliance": ("Arjun Sethi", "arjun.sethi@example.com"),
    "tata": ("Leela Krishnan", "leela.krishnan@example.com"),
}


class FactoryError(RuntimeError):
    pass


def run(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.setdefault("GIT_AUTHOR_DATE", FIXTURE_TIMESTAMP)
    env.setdefault("GIT_COMMITTER_DATE", FIXTURE_TIMESTAMP)
    result = subprocess.run(
        ["git", *args],
        cwd=repo,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        raise FactoryError(
            f"git {' '.join(args)} failed\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    return result


def git_out(repo: Path, *args: str) -> str:
    return run(repo, *args).stdout.strip()


def write(repo: Path, relative_path: str, content: str) -> None:
    path = repo / relative_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def commit(repo: Path, role: str, date: str, message: str) -> str:
    name, email = AUTHORS[role]
    env = os.environ.copy()
    env.update(
        {
            "GIT_AUTHOR_NAME": name,
            "GIT_AUTHOR_EMAIL": email,
            "GIT_COMMITTER_NAME": name,
            "GIT_COMMITTER_EMAIL": email,
            "GIT_AUTHOR_DATE": date,
            "GIT_COMMITTER_DATE": date,
        }
    )
    subprocess.run(["git", "add", "."], cwd=repo, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    result = subprocess.run(
        ["git", "commit", "-m", message],
        cwd=repo,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise FactoryError(f"commit failed: {message}\n{result.stdout}\n{result.stderr}")
    return git_out(repo, "rev-parse", "HEAD")


def make_writable_and_retry(function: Any, path: str, excinfo: BaseException) -> None:
    os.chmod(path, stat.S_IWRITE)
    function(path)


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path, onexc=make_writable_and_retry)
    path.mkdir(parents=True, exist_ok=True)


def available_scenarios() -> list[str]:
    return sorted(path.stem for path in SCENARIOS_DIR.glob("*.yaml"))


def load_scenario(name: str) -> dict[str, Any]:
    path = SCENARIOS_DIR / f"{name}.yaml"
    if not path.exists():
        raise FactoryError(f"unknown scenario '{name}'. Available: {', '.join(available_scenarios())}")

    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text)
    except ModuleNotFoundError:
        data = json.loads(text)

    if not isinstance(data, dict):
        raise FactoryError(f"scenario file did not contain an object: {path}")
    return data


def init_base_history(repo: Path) -> str:
    repo.mkdir(parents=True, exist_ok=True)
    run(repo, "init", "-b", "main", check=False)
    if git_out(repo, "branch", "--show-current") != "main":
        run(repo, "branch", "-m", "main")
    run(repo, "config", "user.name", "CHF Test Repo Bot")
    run(repo, "config", "user.email", "chf-test-repo@example.test")

    write(
        repo,
        "README.md",
        """# CHF Synthetic Test Repo

Generated by `scripts/repo_factory.py`.

This repository models main, release, and A/R/T tenant branches for CHF testing.
""",
    )
    write(
        repo,
        "src/app.py",
        """def greet(tenant):
    return f"hello {tenant}"

def healthcheck():
    return {"status": "healthy"}
""",
    )
    write(
        repo,
        "src/auth/session.py",
        """def validate_token(token, tenant):
    if not token:
        return False
    return token.startswith(f"{tenant}:")
""",
    )
    write(repo, "src/billing/invoice.py", 'def invoice_total(lines):\n    return sum(line["amount"] for line in lines)\n')
    write(repo, "config/runtime.json", '{\n  "session_timeout": 30,\n  "retry_limit": 2\n}\n')
    write(repo, "tenants/airtel/settings.json", '{\n  "tenant": "airtel",\n  "brand": "Airlet"\n}\n')
    write(repo, "tenants/reliance/settings.json", '{\n  "tenant": "reliance",\n  "brand": "Reliance"\n}\n')
    write(repo, "tenants/tata/settings.json", '{\n  "tenant": "tata",\n  "brand": "Tata"\n}\n')
    base_sha = commit(repo, "platform", "2026-01-08T10:00:00+05:30", "feat(core): seed tenant-aware application")

    write(repo, "src/router.py", 'def route(path):\n    return {"path": path, "status": "ok"}\n')
    commit(repo, "platform", "2026-01-17T14:00:00+05:30", "feat(api): add basic router")

    write(repo, "docs/release-notes.md", "## v1.0.0\n- Tenant-aware application skeleton\n- Basic router\n")
    commit(repo, "release", "2026-02-14T16:00:00+05:30", "chore(release): prepare v1.0.0")
    run(repo, "tag", "v1.0.0")
    run(repo, "checkout", "-b", "release/1.0.0")

    run(repo, "checkout", "-b", "tenant/airtel-v1.0.0")
    write(repo, "tenants/airtel/support.md", "# Airtel Support\n\nOwner: Neha Rao\n")
    commit(repo, "airtel", "2026-02-18T13:10:00+05:30", "feat(tenant): onboard Airtel tenant branch")

    run(repo, "checkout", "release/1.0.0")
    run(repo, "checkout", "-b", "tenant/reliance-v1.0.0")
    write(repo, "tenants/reliance/feature-flags.yaml", "tenant:\n  name: reliance\n  flags:\n    new-ui: false\n")
    commit(repo, "reliance", "2026-02-20T15:45:00+05:30", "feat(tenant): add Reliance tenant flags")

    run(repo, "checkout", "release/1.0.0")
    run(repo, "checkout", "-b", "tenant/tata-v1.0.0")
    write(repo, "tenants/tata/network.yaml", "tenant:\n  name: tata\n  dns_zone: tata.example.internal\n")
    commit(repo, "tata", "2026-02-23T12:05:00+05:30", "feat(tenant): add Tata network config")

    run(repo, "checkout", "main")
    write(repo, "src/metrics.py", 'def record(event):\n    return {"recorded": event}\n')
    commit(repo, "platform", "2026-03-08T10:20:00+05:30", "feat(observability): add request metrics")
    write(repo, "src/cache.py", '_cache = {}\n\ndef get(key):\n    return _cache.get(key)\n\ndef set(key, value):\n    _cache[key] = value\n')
    commit(repo, "platform", "2026-03-24T09:40:00+05:30", "feat(core): add in-memory config cache")
    write(repo, "docs/release-notes.md", "## v1.1.0\n- Request metrics\n- In-memory config cache\n")
    commit(repo, "release", "2026-04-12T17:00:00+05:30", "chore(release): prepare v1.1.0")
    run(repo, "tag", "v1.1.0")
    run(repo, "checkout", "-b", "release/1.1.0")
    return base_sha


def plant_clean_cherry_pick(repo: Path) -> tuple[str, list[str]]:
    run(repo, "checkout", "release/1.0.0")
    write(repo, "src/billing/invoice.py", 'def invoice_total(lines):\n    total = sum(line["amount"] for line in lines)\n    return round(total, 2)\n')
    return commit(repo, "release", "2026-06-20T10:00:00+05:30", "fix(billing): round invoice totals"), []


def plant_conflicting_cherry_pick(repo: Path) -> tuple[str, list[str]]:
    run(repo, "checkout", "release/1.0.0")
    write(repo, "src/auth/session.py", 'def validate_token(token, tenant):\n    if not token:\n        return False\n    normalized = token.strip()\n    return normalized.startswith(f"{tenant}:")\n')
    source_sha = commit(repo, "release", "2026-06-21T10:00:00+05:30", "fix(auth): trim token before validation")
    run(repo, "checkout", "tenant/reliance-v1.0.0")
    write(repo, "src/auth/session.py", 'def validate_token(token, tenant):\n    if not token:\n        return False\n    if tenant == "reliance" and token.startswith("legacy:"):\n        return True\n    return token.startswith(f"{tenant}:")\n')
    commit(repo, "reliance", "2026-06-21T11:00:00+05:30", "fix(auth): allow Reliance legacy token prefix")
    return source_sha, []


def plant_rewritten_history(repo: Path) -> tuple[str, list[str]]:
    run(repo, "checkout", "release/1.0.0")
    patch = 'def invoice_total(lines):\n    subtotal = sum(line["amount"] for line in lines)\n    return round(subtotal, 2)\n'
    write(repo, "src/billing/invoice.py", patch)
    source_sha = commit(repo, "release", "2026-06-22T10:00:00+05:30", "fix(billing): stabilize invoice rounding")
    run(repo, "checkout", "tenant/tata-v1.0.0")
    write(repo, "src/billing/invoice.py", patch)
    commit(repo, "tata", "2026-06-22T11:00:00+05:30", "fix(billing): apply Tata invoice rounding patch")
    return source_sha, []


def plant_generated_files(repo: Path) -> tuple[str, list[str]]:
    run(repo, "checkout", "release/1.0.0")
    write(repo, "config/runtime.json", '{\n  "session_timeout": 30,\n  "retry_limit": 2,\n  "feature_flag": "tenant-safe-cache"\n}\n')
    write(repo, "dist/generated_config.json", '{"session_timeout":30,"retry_limit":2,"feature_flag":"tenant-safe-cache"}\n')
    return commit(repo, "release", "2026-06-23T10:00:00+05:30", "fix(config): add tenant safe cache flag and generated output"), []


def plant_missing_dependency_commit(repo: Path) -> tuple[str, list[str]]:
    run(repo, "checkout", "release/1.0.0")
    write(repo, "config/schema.py", 'REQUIRED_KEYS = ["tenant", "brand", "session_timeout"]\n')
    dependency_sha = commit(repo, "release", "2026-06-24T10:00:00+05:30", "feat(config): add tenant schema constants")
    write(repo, "src/auth/session.py", 'from config.schema import REQUIRED_KEYS\n\n\ndef validate_token(token, tenant):\n    if "tenant" not in REQUIRED_KEYS:\n        return False\n    if not token:\n        return False\n    return token.startswith(f"{tenant}:")\n')
    source_sha = commit(repo, "release", "2026-06-24T11:00:00+05:30", "fix(auth): validate token using tenant schema")
    return source_sha, [dependency_sha]


def plant_dirty_worktree(repo: Path) -> tuple[str, list[str]]:
    source_sha, deps = plant_clean_cherry_pick(repo)
    run(repo, "checkout", "tenant/tata-v1.0.0")
    write(repo, "tenants/tata/settings.json", '{\n  "tenant": "tata",\n  "brand": "Tata",\n  "dirty": true\n}\n')
    return source_sha, deps


PLANTERS = {
    "clean_cherry_pick": plant_clean_cherry_pick,
    "conflicting_cherry_pick": plant_conflicting_cherry_pick,
    "rewritten_history": plant_rewritten_history,
    "generated_files": plant_generated_files,
    "missing_dependency_commit": plant_missing_dependency_commit,
    "dirty_worktree": plant_dirty_worktree,
}


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def build_expected(
    scenario: dict[str, Any],
    repo: Path,
    base_sha: str,
    source_sha: str,
    dependency_shas: list[str],
) -> dict[str, Any]:
    target_branch = scenario["target_branch"]
    source_branch = scenario["source_branch"]
    run(repo, "checkout", target_branch)
    return {
        "schema_version": "1.0",
        "artifact_type": "repo_factory_expected",
        "scenario": scenario["name"],
        "description": scenario["description"],
        "created_at": "2026-06-01T00:00:00Z",
        "repo_path": str(repo),
        "branches": {
            "main": "main",
            "source": source_branch,
            "target": target_branch,
            "tenants": [
                "tenant/airtel-v1.0.0",
                "tenant/reliance-v1.0.0",
                "tenant/tata-v1.0.0",
            ],
        },
        "tenant": scenario["tenant"],
        "base_sha": base_sha,
        "source_branch_tip": git_out(repo, "rev-parse", source_branch),
        "target_branch_tip": git_out(repo, "rev-parse", target_branch),
        "source_shas": [source_sha],
        "dependency_shas": dependency_shas,
        "expected_result": scenario["expected_result"],
        "confidence": "high",
        "strategy": scenario["strategy"],
        "blockers": scenario["blockers"],
        "generated_files": scenario["generated_files"],
        "evidence_commands": [
            f"git checkout {target_branch}",
            "git status --short",
            f"git cherry-pick {source_sha}",
        ],
    }


def build_scenario(name: str, output: Path) -> Path:
    scenario = load_scenario(name)
    scenario_dir = output / name
    repo = scenario_dir / "repo"
    reset_dir(scenario_dir)
    base_sha = init_base_history(repo)
    source_sha, dependency_shas = PLANTERS[name](repo)
    write_json(scenario_dir / "scenario.json", scenario)
    expected = build_expected(scenario, repo, base_sha, source_sha, dependency_shas)
    expected_path = scenario_dir / "expected.json"
    write_json(expected_path, expected)
    write_json(
        scenario_dir / "manifest.json",
        {
            "scenario": name,
            "expected_sha256": hashlib.sha256(expected_path.read_bytes()).hexdigest(),
        },
    )
    return scenario_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario", help="Scenario name, or all.")
    parser.add_argument("--output", default="./output", help="Output directory.")
    parser.add_argument("--list", action="store_true", help="List available scenarios.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.list:
        print("\n".join(available_scenarios()))
        return 0
    if not args.scenario:
        raise FactoryError("--scenario is required unless --list is used")

    names = available_scenarios() if args.scenario == "all" else [args.scenario]
    output = Path(args.output).resolve()
    output.mkdir(parents=True, exist_ok=True)

    print("Built fixtures:")
    for name in names:
        print(f"  {build_scenario(name, output)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
